### PR TITLE
Fix stereo camera resolution

### LINKED ISSUE #18: [yolov4_publisher.launch] Depth image size and camera info don't match
Thanks for the great product.

When I run yolov4_publisher.launch and try to see DepthCloud in rviz, I get the following error.

```
Message
Error updating depth cloud: Depth image size and camera info don't match: 640 x 400 vs 1280 x 720(binning: 1 x 1, ROI size: 1280 x 720)
```
image

Hardware: OAK-D

If you modify the following part to `THE_720_P` instead of `THE_400_P`, DepthCloud will be output without problems.  

https://github.com/luxonis/depthai-ros-examples/blob/e9f2fd604f0cee291e30152be57fc7283f6f12c8/depthai_examples/ros1_src/yolov4_spatial_publisher.cpp#L54-L56

image

May I send a PR?

### PR DESCRIPTION
**Pull request by h-wata**
* Adapted to the resolution of the OAK-D device. 
* fix #18 .

### CODE REVIEW

**Review by saching13 — CHANGES_REQUESTED** [review]
Thanks a lot for the PR. And sorry for creating the bug in the first place. If possible can you make the resolution selectable from an argument with 720 as default?

**Comment by saching13** [comment]
and also use the method [here](https://github.com/luxonis/depthai-ros-examples/blob/e9f2fd604f0cee291e30152be57fc7283f6f12c8/depthai_examples/ros1_src/stereo_nodelet.cpp#L83) to get the calibInfo from the device instead of the default files.

**Comment by h-wata** [comment]
Thank you for your review. 
In response to your comment, I have modified the resolution so that you can select it from rosparam.

> Thanks a lot for the PR. And sorry for creating the bug in the first place. If possible can you make the resolution selectable from an argument with 720 as default?

But I don't have a ROS2 environment, so I can't verify whether the build will pass or not, so I need to test it in ROS2 environment.

I will work on the second comment.

> and also use the method [here](https://github.com/luxonis/depthai-ros-examples/blob/e9f2fd604f0cee291e30152be57fc7283f6f12c8/depthai_examples/ros1_src/stereo_nodelet.cpp#L83) to get the calibInfo from the device instead of the default files.

**Comment by saching13** [comment]
> Thank you for your review. In response to your comment, I have modified the resolution so that you can select it from rosparam.
> 
> > Thanks a lot for the PR. And sorry for creating the bug in the first place. If possible can you make the resolution selectable from an argument with 720 as default?
> 
> But I don't have a ROS2 environment, so I can't verify whether the build will pass or not, so I need to test it in ROS2 environment.
> 
> I will work on the second comment.
> 
> > and also use the method [here](https://github.com/luxonis/depthai-ros-examples/blob/e9f2fd604f0cee291e30152be57fc7283f6f12c8/depthai_examples/ros1_src/stereo_nodelet.cpp#L83) to get the calibInfo from the device instead of the default files.

No worries on ROS2 env. LMK after the changes. I will test the ROS2 and get back to you.

**Comment by h-wata** [comment]
It's ready, please review it at your convenience.

File: depthai_examples/ros1_src/yolov4_spatial_publisher.cpp [hunk 1]
```diff
@@ -1,6 +1,7 @@
 
 #include "ros/ros.h"
 
+#include <depthai-shared/properties/MonoCameraProperties.hpp>
```
Comment (themarpe) [inline depthai_examples/ros1_src/yolov4_spatial_publisher.cpp]: Include  
```
#include <depthai/pipeline/node/MonoCamera.hpp>
```

And use `dai::node::MonoCamera::Properties::SensorResolution`, etc... instead

**Review by themarpe — CHANGES_REQUESTED** [review]

File: depthai_examples/ros1_src/yolov4_spatial_publisher.cpp [hunk 2]
```diff
@@ -125,14 +140,20 @@ int main(int argc, char** argv){
...
+    std::shared_ptr<dai::DataOutputQueue> stereoQueue;
+    auto calibrationHandler = _dev->readCalibration();
+
+    //TODO this part would be removed once we have calibration-api
     std::string color_uri = camera_param_uri + "/" + "color.yaml";
-     std::string stereo_uri = camera_param_uri + "/" + "right.yaml";
 
-    dai::rosBridge::ImageConverter rgbConverter(deviceName + "_rgb_camera_optical_frame", false);
-    dai::rosBridge::BridgePublisher<sensor_msgs::Image, dai::ImgFrame> rgbPublish(device.getOutputQueue("preview", 30, false),
+    dai::rosBridge::BridgePublisher<sensor_msgs::Image, dai::ImgFrame> rgbPublish(colorQueue,
```
Comment (saching13) [inline depthai_examples/ros1_src/yolov4_spatial_publisher.cpp]: `auto rgbCameraInfo = rgbtConverter->calibrationToCameraInfo(calibrationHandler, dai::CameraBoardSocket::RGB, width, height)`

You can do the same for RGB camera too instead of using color.yaml

File: depthai_examples/ros1_src/yolov4_spatial_publisher.cpp [hunk 3]
```diff
@@ -51,9 +56,17 @@ dai::Pipeline createPipeline(bool syncNN, bool subpixel, std::string nnPath, int
...
     colorCam->setColorOrder(dai::ColorCameraProperties::ColorOrder::BGR);
 
-    monoLeft->setResolution(dai::MonoCameraProperties::SensorResolution::THE_400_P);
+    if(resolution == "720p"){
+        monoResolution = dai::MonoCameraProperties::SensorResolution::THE_720_P; 
+    }else if(resolution == "400p" ){
+        monoResolution = dai::MonoCameraProperties::SensorResolution::THE_400_P; 
+    }else{
+        monoResolution = dai::MonoCameraProperties::SensorResolution::THE_800_P; 
+    }
```
Comment (saching13) [inline depthai_examples/ros1_src/yolov4_spatial_publisher.cpp]: can you validate if `800p` is passed on the string too ? and throw an error on else if it has an invalid string. 
And there is 480p res too (Which is for OAK-D-LITE) we can add that too here.

**Review by saching13 — CHANGES_REQUESTED** [review]

File: depthai_examples/ros2_src/yolov4_spatial_publisher.cpp [hunk 4]
```diff
@@ -51,9 +52,16 @@ dai::Pipeline createPipeline(bool syncNN, bool subpixel, std::string nnPath, int
...
     colorCam->setColorOrder(dai::ColorCameraProperties::ColorOrder::BGR);
 
-    monoLeft->setResolution(dai::MonoCameraProperties::SensorResolution::THE_400_P);
+    if(resolution == "720p"){
+        monoResolution = dai::MonoCameraProperties::SensorResolution::THE_720_P; 
+    }else if(resolution == "400p" ){
+        monoResolution = dai::MonoCameraProperties::SensorResolution::THE_400_P; 
+    }else{
+        monoResolution = dai::MonoCameraProperties::SensorResolution::THE_800_P; 
+    }
```
Comment (saching13) [inline depthai_examples/ros2_src/yolov4_spatial_publisher.cpp]: Same as in ros1

File: depthai_examples/ros2_src/yolov4_spatial_publisher.cpp [hunk 5]
```diff
@@ -127,15 +138,20 @@ int main(int argc, char** argv){
...
+
+    auto calibrationHandler = device.readCalibration();
+
     std::string color_uri = camera_param_uri + "/" + "color.yaml";
-    std::string stereo_uri = camera_param_uri + "/" + "right.yaml";
 
     //TODO(sachin): Add option to use CameraInfo from EEPROM
     dai::rosBridge::ImageConverter rgbConverter(deviceName + "_rgb_camera_optical_frame", false);
-    dai::rosBridge::BridgePublisher<sensor_msgs::msg::Image, dai::ImgFrame> rgbPublish(device.getOutputQueue("preview", 30, false),
+    dai::rosBridge::BridgePublisher<sensor_msgs::msg::Image, dai::ImgFrame> rgbPublish(colorQueue,
```
Comment (saching13) [inline depthai_examples/ros2_src/yolov4_spatial_publisher.cpp:157]: Same as in ros1

**Review by saching13 — CHANGES_REQUESTED** [review]

File: depthai_examples/ros1_src/yolov4_spatial_publisher.cpp (hunk 2 above)
Comment (h-wata) [reply depthai_examples/ros1_src/yolov4_spatial_publisher.cpp]: Thanks.
I apologize for my lack of understanding.
Should the height and width match the preview(416,416) or the 1080p(1920, 1080)?

File: depthai_examples/ros1_src/yolov4_spatial_publisher.cpp (hunk 1 above)
Comment (h-wata) [reply depthai_examples/ros1_src/yolov4_spatial_publisher.cpp]: Fixed in b9b6b81.

File: depthai_examples/ros1_src/yolov4_spatial_publisher.cpp (hunk 3 above)
Comment (h-wata) [reply depthai_examples/ros1_src/yolov4_spatial_publisher.cpp]: Fixed in b9b6b81.

File: depthai_examples/ros1_src/yolov4_spatial_publisher.cpp (hunk 2 above)
Comment (h-wata) [reply depthai_examples/ros1_src/yolov4_spatial_publisher.cpp]: Fixed in b9b6b81. 
CameraInfo match (416, 416). If I misunderstood, please comment.

File: depthai_examples/ros2_src/yolov4_spatial_publisher.cpp (hunk 4 above)
Comment (h-wata) [reply depthai_examples/ros2_src/yolov4_spatial_publisher.cpp]: Fixed in b9b6b81.

File: depthai_examples/ros2_src/yolov4_spatial_publisher.cpp (hunk 5 above)
Comment (h-wata) [reply depthai_examples/ros2_src/yolov4_spatial_publisher.cpp:157]: Fixed in b9b6b81.

File: depthai_examples/ros1_src/yolov4_spatial_publisher.cpp [hunk 6]
```diff
@@ -28,9 +29,13 @@ const std::vector<std::string> label_map = {"person",         "bicycle",    "car
              "laptop",         "mouse",      "remote",        "keyboard",      "cell phone",  "microwave",     "oven",
              "toaster",        "sink",       "refrigerator",  "book",          "clock",       "vase",          "scissors",
              "teddy bear",     "hair drier", "toothbrush"};
+std::unique_ptr<dai::rosBridge::BridgePublisher<sensor_msgs::Image, dai::ImgFrame>> rgbPublish, depthPublish;
+std::unique_ptr<dai::rosBridge::ImageConverter> rgbConverter, rightConverter;
```
Comment (saching13) [inline depthai_examples/ros1_src/yolov4_spatial_publisher.cpp]: Any specific reason why unique ptr is created here ?

Comment (h-wata) [reply depthai_examples/ros1_src/yolov4_spatial_publisher.cpp]: The following parts have been followed. 
https://github.com/luxonis/depthai-ros-examples/blob/e9f2fd604f0cee291e30152be57fc7283f6f12c8/depthai_examples/ros1_src/stereo_nodelet.cpp#L21-L23
There is no particular reason to do otherwise. 
If it is unnecessary, we will correct it.

Comment (h-wata) [reply depthai_examples/ros1_src/yolov4_spatial_publisher.cpp]: I checked it works with OAK-D and OAK-D-LITE.
The unique_ptr was being used unnecessarily, so I changed it back.

**Review by saching13 — APPROVED** [review]
